port: 8081
path: /media/
webhookType: 'bark'
# webhooks: 'https://open.feishu.cn/open-apis/bot/v2/hook/1a574278-1c35-4b7a-9084-0844d4bd0603'
webhooks: 'https://api.day.app/wmKLMC4xdxL9djWCMc3SWP/$TEXT/文件下载成功'
thread: false
downloadThread: true
useFFmpegLib: true