port: 8081
downloadDir: /media/
webhooks: https://bark.helson-lin.cn/Mtf2nA8kE4wYrMuQNHunDo/$TEXT
webhookType: bark
thread: true
useFFmpegLib: true
maxDownloadNum: 2
preset: medium
outputformat: mp4
enableTimeSuffix: false
