port: 8081
downloadDir: /media/
webhooks: 'https://open.feishu.cn/open-apis/bot/v2/hook/ec34fee9-5695-4e2d-8938-129e71656ad2'
webhookType: feishu
thread: true
useFFmpegLib: true
maxDownloadNum: 5
preset: ultrafast
outputformat: mp4
enableTimeSuffix: false
